const fs = require('fs');
const assert = require('assert');
const retail = fs.readFileSync('GearExport-Retail.toc', 'utf8');
assert(/^## Interface: 120100$/m.test(retail), 'Retail target must match audited 12.1.0');
const files = toc => toc.split(/\r?\n/).filter(line => line.endsWith('.lua'));
const expected = files(fs.readFileSync('GearExport.toc', 'utf8')).filter(file => file !== 'BankCleanup.lua');
expected.push('WoWSyncGuildBankDiagnostic.lua');
assert.deepStrictEqual(files(retail), expected, 'Retail must use the same implementation and load order, excluding BankCleanup');
assert(!retail.includes('BankCleanup.lua'), 'Retail must not load Classic bank actions');
assert(!fs.existsSync('dist/Forever/GearExport/WoWSyncGuildBankDiagnostic.lua'), 'Guild Bank diagnostic is Retail-only');
assert(retail.includes('## SavedVariables: GearExportDB, WoWSyncDB'), 'Shared database schema');
for (const file of files(retail)) assert(fs.existsSync(file), 'Missing package source ' + file);
console.log('PASS: Retail interface, shared source/load order, SavedVariables and BankCleanup exclusion');
